Проект №13: Функциональность «Удаление фильмов и пользователей"
Ivan-Vorobev/java-filmorate pull request #13
Opened 2024-10-29 10:14 UTC by Irina-Gavrilina

2024-10-29 15:32 UTC, farrukhrus requested changes

2024-10-29 15:32 UTC, farrukhrus commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> -    @Test
Тесты валятся?

2024-10-29 15:32 UTC, farrukhrus commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> -    @Test
Можем раскомментить тест?

2024-10-29 20:39 UTC, farrukhrus approved these changes

2024-10-30 08:44 UTC, Irina-Gavrilina commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> -    @Test
Тесты переписала, теперь работают

2024-10-30 18:29 UTC, merged