Проект №11: Реализация ТЗ
Ivan-Vorobev/java-filmorate pull request #3
Opened 2024-10-07 23:34 UTC by Ivan-Vorobev

2024-10-08 13:59 UTC, tomattman requested changes
Комменты в коде

2024-10-08 13:59 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Set<Long> filmLikes = likes.get(film.getId());
если фильма нету то вернет null а стоит либо кинуть ошибку, если фильм не найден, либо вернуть пустой список

2024-10-08 13:59 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Set<Long> filmLikes = likes.get(film.getId());
а все вижу внизу, но как то очень запутанно воспринимается
почему бы при создании фильма не создавать сразу пустой список лайков для него

хотя конечно и так можно оставить, но раз вопрос возник, то значит улучшить можно)

2024-10-09 01:49 UTC, Ivan-Vorobev commented on pom.xml
> +		<dependency>
Это из ТЗ:
```
Также подключите к проекту дополнительный стартер:
Этот стартер интегрирует в Spring Framework [библиотеку Logbook](https://github.com/zalando/logbook). Она будет выводить в лог информацию об HTTP-запросах и ответах.
```

2024-10-09 02:07 UTC, Ivan-Vorobev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public static class ErrorResponse {
Вынесу когда потребуется переиспользование

2024-10-09 02:51 UTC, Ivan-Vorobev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Set<Long> filmLikes = likes.get(film.getId());
Добавил лайки и список друзей при создании сущностей. Почистил все репозитории от выброса ошибок, переложив эту логику в сервис (я так полагаю у нас далее будут репозитории с базой и там не нужно будет повторять логику с проверкой null не null)

2024-10-09 11:08 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Set<Long> filmLikes = likes.get(film.getId());
все будет зависеть от того как ты сделаешь, в этом проекте вы будете запросы в базу реализовывать сами, поэтому тут с одной стороны проще, так как как хотите так и делаете, в другой стороны тяжелее, ведь самим прийдетсявсе реализовывать

но как я уже писал в другом комментарии, рекомендую, перевести запросы которые возвращают один обьект на то, чтобы они возвращали Optional

2024-10-09 11:09 UTC, tomattman reviewed
привет, остались моменты на улучшить, в основном с прошлого пулл реквеста, 
но принято

2024-10-09 11:10 UTC, tomattman approved these changes

2024-10-10 04:58 UTC, merged