Проект №12: Проект по SQL
Ivan-Vorobev/java-filmorate pull request #4
Opened 2024-10-20 22:03 UTC by Ivan-Vorobev

2024-10-21 08:17 UTC, tomattman requested changes
Привет, один основной момент, join в запросах
остальное мелочи

2024-10-21 08:17 UTC, tomattman commented on scheme.png
ganer -> genre

2024-10-21 08:17 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final BadRequestException e) {
стоит давать более понятные имена методам, если обрабатываем BadRequestException то лучше назвать handleBadRequestException

2024-10-21 08:17 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.film;
очень тяжело воспринимается, когда базовый класс, в каком то совершенно другом пакете

2024-10-21 08:17 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return filmBaseStorage.findMany(FIND_ALL_QUERY);
должен быть запрос с join как минимум для mpa
в лучшем случае для любого количества фильмов максимум два запроса

2024-10-21 08:17 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return filmBaseStorage.findOne(FIND_BY_ID_QUERY, filmId);
аналогично

2024-10-21 08:17 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        FilmDto filmDto = filmStorage
я уже расписывал это другому студенту в другом ревью, но стоит сделать запросы с Join как минимум для mpa 
просто чтобы показать что ты умеешь этим пользоваться

2024-10-21 08:33 UTC, Ivan-Vorobev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final BadRequestException e) {
Копипаста
FIXed

2024-10-22 08:02 UTC, tomattman approved these changes
Принято, но обрати внимание на комменты что я оставил

2024-10-22 08:02 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            LEFT JOIN film_genres fj ON fj.film_id = f.id
тут есть сразу плюс и минус в join жанров
с одной стороны только один запрос
с другой стороны если у тебя будет у одного фильма 5 жанров, то прийдет 5 копий данных о фильмах
и пока это запрос на один фильм то нет проблем, а если таких фильмов 100, и вместо 100 записей прийдет 500 

хороший вариант реализовать - получить с join mpa рейтинг
а жанры получить вторым запросом и потом в коде их срастить

2024-10-22 08:02 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/dto/FilmDto.java
> +package ru.yandex.practicum.filmorate.storage.dal.dto;
тут будет еще про пакеты
DTO не относится к слоб доступа к данным, чаще всего они относятся к слоб контроллера или/и сервиса стоит там и хранить
второе - мапперы можно было бы раскидать по пакетам с соответствующими хранилищами
третье, рекомендую называть пакеты в единственном числе

2024-10-22 08:21 UTC, merged